### ISSUE TITLE
Dialog not displayed

### ISSUE THREAD

**Issue by boogiebit** [CreativeIT/material-angular-dashboard#31]
Hi, I'm trying to implement material dialog in my project but the dialog opens at the bottom of the layout with green background.

Anyone else having the same issue?

**Comment by gabri3l0** [comment]
How you can display dialog? Can i have to install something?

**Comment by gabri3l0** [comment]
@bor-yo Try to put on style.scss 
```
@import '~@angular/material/prebuilt-themes/pink-bluegrey.css';
```

**Comment by gabri3l0** [comment]
Another answer is [problem with modalDialog](https://stackoverflow.com/questions/60949170/cannot-import-matdialogmodule-in-app-module)

**Comment by maxwellCatCoder** [comment]
Hello. My friend, unfortunately, you haven't provided enough information to deal with this issue.
Please, open the new issue using the following template https://github.com/stevemao/github-issue-templates/blob/master/simple/ISSUE_TEMPLATE.md if your problem is not resolved. Best regards, CreativeIT.
